

s = "AGTCGGTGTTACGCTCCGGTAACGTTGAGAGAGACACGCGACGAATCTCTCGGCTCGTGGAGCTATATATTGTTTATTATCCGTCTGGCGTGAATAGCGTTATGGAGCCTACATTGCGTGTTGGTTGGGGTCGCCGGGGAAAAATAATTTTGAATCATCGCGCATTTCGGACGATCCGTACTTTAAAAGTCATTACGTTCACATGTTACATAAAGTGGATTCCATCCGCGATCATTCGTGATAATACCGTACAGGTCATCGGGTCTTGTACCCTAGCCTGAACCCTGTTCACGTGGCGCACGGGTGAAAGAAAGCTGAGCCACAGTACAAAGCAATGATAGCTGGTTATTTTACGTGTTTAGGGTGAGAGGTCCAGTTGTTAGGATGTTTCAGGCTTATCCGTTCTCATATATGGTTACAGCGTACGTGTGCCCGCTTTTGTACTGAATTTTGCGAGGCTTCGATGGTACAAGTCGGCCATTTATGTGTGGGCCCTCAATGTGGCGCCATGGATCAGCCATCACGGTAGTGGCACTCAGACTAACTTCTCCTAACTCTTAGCAGTAAATATTCCTTGGTTGACTGCGGGACAGCCCACAAGCGGAGAGAAAGGTCCTAACCAGAAGTTCGGCCCAGGCTTCCGGGGCACGAGGCAATCTTAAGGCTATGAAAATGCACGATAAAGACTAGAATCTGTGGCGGGAATTTGGGCCCGTCTGAAGCTAATCGGCAATTCAGTGAATAAAATGTGTGTACCGTCTAACACTGACCCATCGGAGAAGCTACACAAAATCTTGGCATTGCCTATAGTCCAGGCAGATAGTTAACCTACTAGCCGATG"
cnt_A = 0
cnt_C = 0
cnt_G = 0
cnt_T = 0

for nuc in s:
  if (nuc == 'A'):
    cnt_A += 1
  elif(nuc == 'C'):
    cnt_C += 1
  elif(nuc == 'G'):
    cnt_G += 1
  elif(nuc == 'T'):
    cnt_T += 1

return array(cnt_A,cnt_C,cnt_G,cnt_T)