


def transcribe_RNA(dna):
    dna = dna.upper()
    rna_strand = ""
    for x in dna:
        base = check_base(x)
        rna_strand += base
    print("DNA: " + dna)
    rna_strand = rna_strand[::-1]
    print("RNA: " + rna_strand)

def check_base(base):
    if (base == 'A'):
        return 'T'
    elif (base == 'G'):
        return 'C'
    elif (base == 'T'):
        return 'A'
    elif (base == 'C'):
        return 'G'
    else:
        raise("Not a valid base")    

transcribe_RNA("TAACGACACCTTAGGTAATCCCCATTAACCTAGTACCGTCATAGGTGGGCGCTAACATACGAACCGTTACAGAGTTTTCGCTCCCTTTAGGAGACAACGGTGTCGTTTTTAGTGGTCCTCTACTCCTGCTAGGAAGGTTTAGAAGTAGTTTGGACCGCCTTTTCTCGTGCAAATGCATGTTCACAGAACGTGTGTTATCCCATAATGTAAGGGACCGAAAGCGCTCGAGACGAATGTAAAACAGCCAAGGTCCCTAACCTAGTAAGGGTGGTGATAACTTTACGCTCAACCTCAACGCAGGGCCACCCTTCCGGGGCTTAGTAGGAGGTCGCGAATCATATATGGCCTACGGCTATAATTGCGACCGCCAACCGTGAGGTGTTAACGACAAAAATGTGAAGATTTGTAGACACACTCATTCTCCCCAGCTGCGACGAGTGTCCTCTATTAGTGTAATACCGAAAGGTTAAGAGTCGCTGCTAAATATTGGCATGATCTAGCTCGAATGCGCATCGAAGTCTTCTGTGTGTCTGAACGGACCCATGCAAGTTCAATTTGCCTTGTCGTACGTCATTGGTGAACTTCATGATCGGATGAGGCACGTAAGGCGCCTCAGTCCTTAGGAATACTCGTTATTAGGCTGCCACATTGTCCATGGCTAGCCTCGCCGCAGTGGATATATAGATCGGAATGGAACGTAGGAAAGAATCGGTAGGCGCAGGTATAGTACGTTAGTCCCTTCTGCCGACAAGCTGAGTTTCATCATCGGAAACACCAATGAGATACATATGACAGACATACACCGTCTTATTTACCATGGGCGCATCTGCCCGTACAGACGGGGTGCCGCGGAACATAAAGAATTTAACACGTGCAGTATCAAAGCACGACGGCAATTGCGGCACCTGTGGAGAACGTTATGGCGTAGGTGTGAGCCGCGCTAGTTAGCGAATGAAA")


#def translate_protein(rna):





